from datetime import datetime
import sys
sys.path.append('.')

# Parts database for realistic recommendations
PARTS_DATABASE = {
    'Fan bearing':      {'part': 'SKF 6205-2RS Bearing',   'cost': 340,   'labor': 800},
    'Compressor blade': {'part': 'OEM Compressor Blade Set','cost': 2400,  'labor': 3200},
    'Fuel injector':    {'part': 'Parker Fuel Injector',    'cost': 890,   'labor': 600},
    'Seal':             {'part': 'High-Temp Ceramic Seal',  'cost': 180,   'labor': 400},
    'Turbine blade':    {'part': 'OEM Turbine Blade',       'cost': 4200,  'labor': 5000},
    'Cooling system':   {'part': 'Cooling Passage Kit',     'cost': 560,   'labor': 1200},
    'Bleed valve':      {'part': 'Pneumatic Bleed Valve',   'cost': 720,   'labor': 500},
    'General':          {'part': 'Maintenance Kit',         'cost': 1200,  'labor': 2000},
}

FAILURE_COSTS = {
    'NORMAL':   0,
    'LOW':      5000,
    'MEDIUM':   25000,
    'HIGH':     150000,
    'CRITICAL': 500000,
}

class ReportGenerator:
    """
    Generates professional plain-English maintenance reports.
    No AI API needed — uses smart templates with real data.
    
    Factory workers get actionable reports, not probability scores.
    This is what separates good AI systems from great ones.
    """
    
    def generate_report(self, engine_id, anomaly_prob,
                        severity, root_cause, timeline,
                        sensor_importance, action_plan):
        """
        Generate complete professional maintenance report.
        
        Returns formatted report as string.
        """
        now = datetime.now()
        report_id = f"RPT-{now.strftime('%Y%m%d')}-E{engine_id:03d}"
        
        # Determine primary component from root cause
        component = self._identify_component(root_cause)
        parts_info = PARTS_DATABASE.get(component, PARTS_DATABASE['General'])
        
        # Calculate costs
        repair_cost = parts_info['cost'] + parts_info['labor']
        failure_cost = FAILURE_COSTS.get(severity, 25000)
        savings = failure_cost - repair_cost
        
        # Top 3 sensors
        top_sensors = list(sensor_importance.items())[:3]
        
        report = f"""
╔══════════════════════════════════════════════════════════════╗
║           PREDICTIVE MAINTENANCE REPORT                      ║
║           {report_id}                              ║
╚══════════════════════════════════════════════════════════════╝

📅 Generated  : {now.strftime('%Y-%m-%d %H:%M:%S')}
🏭 Engine ID  : Engine #{engine_id:03d}
⚠️  Alert Level : {severity}
📊 Confidence  : {round((1 - abs(anomaly_prob - 0.5) * 2) * 100 + 50, 1)}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔍 WHAT IS HAPPENING
{self._get_plain_english_description(severity, component, anomaly_prob)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📡 SENSORS TRIGGERING THIS ALERT
{self._format_sensor_section(top_sensors)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⏰ FAILURE TIMELINE
  Estimated RUL    : {timeline.get('rul_days', 'N/A')} days 
                     ({timeline.get('rul_cycles', 'N/A')} cycles)
  Failure Window   : {timeline.get('earliest_failure_date', 'N/A')} 
                     to {timeline.get('latest_failure_date', 'N/A')}
  ⚡ ACT BEFORE    : {timeline.get('recommended_maintenance', 'N/A')}
  Days Remaining   : {timeline.get('days_until_maintenance', 'N/A')} days

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔧 RECOMMENDED ACTIONS
{self._format_actions(action_plan, severity)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔩 PARTS & LABOR ESTIMATE
  Component        : {component}
  Recommended Part : {parts_info['part']}
  Parts Cost       : ${parts_info['cost']:,}
  Labor Cost       : ${parts_info['labor']:,}
  ─────────────────────────────
  Total Repair     : ${repair_cost:,}
  Cost if Ignored  : ${failure_cost:,}
  💰 YOU SAVE      : ${max(0, savings):,}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✅ SIGN-OFF CHECKLIST
  □ Maintenance team notified
  □ Parts ordered: {parts_info['part']}
  □ Shutdown scheduled: {timeline.get('recommended_maintenance', 'TBD')}
  □ Post-maintenance inspection planned
  □ Report filed in maintenance log

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Generated by Edge AI Predictive Maintenance System v2.0
  Model: Dual-Head Transformer | Dataset: NASA Turbofan
  This report was auto-generated. Verify with qualified engineer.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
        return report.strip()
    
    def _get_plain_english_description(self, severity, component, prob):
        descriptions = {
            'NORMAL': f"Engine is operating within normal parameters. "
                      f"No immediate action required. Continue routine monitoring.",
            
            'LOW':    f"Minor anomaly detected in {component} area. "
                      f"Readings are slightly outside normal range ({prob:.0%} confidence). "
                      f"Schedule inspection during next planned maintenance.",
            
            'MEDIUM': f"Moderate degradation detected in {component}. "
                      f"Pattern suggests early-stage wear ({prob:.0%} confidence). "
                      f"A factory worker should NOT operate this engine past "
                      f"the recommended maintenance date without inspection.",
            
            'HIGH':   f"SIGNIFICANT FAULT DETECTED in {component}. "
                      f"AI model is {prob:.0%} confident of developing failure. "
                      f"Engine should be inspected within 48 hours. "
                      f"Reduce operational load immediately.",
            
            'CRITICAL': f"IMMINENT FAILURE RISK in {component}. "
                        f"AI model shows {prob:.0%} failure probability. "
                        f"STOP ENGINE if safe to do so. "
                        f"Catastrophic failure could occur without immediate action.",
        }
        return descriptions.get(severity, f"Anomaly detected. Probability: {prob:.0%}")
    
    def _identify_component(self, root_cause):
        root_lower = root_cause.lower()
        if 'fan' in root_lower:        return 'Fan bearing'
        if 'compressor' in root_lower: return 'Compressor blade'
        if 'fuel' in root_lower:       return 'Fuel injector'
        if 'seal' in root_lower:       return 'Seal'
        if 'turbine' in root_lower:    return 'Turbine blade'
        if 'cooling' in root_lower:    return 'Cooling system'
        if 'bleed' in root_lower:      return 'Bleed valve'
        return 'General'
    
    def _format_sensor_section(self, top_sensors):
        lines = []
        for sensor_key, info in top_sensors:
            bar_len = int(info['importance_pct'] / 5)
            bar = '█' * bar_len + '░' * (20 - bar_len)
            lines.append(
                f"  {info['name']:<30} [{bar}] {info['importance_pct']}%"
            )
        return '\n'.join(lines) if lines else "  No specific sensor anomaly detected."
    
    def _format_actions(self, action_plan, severity):
        if not action_plan:
            return "  Continue normal monitoring."
        lines = []
        for i, action in enumerate(action_plan[:5], 1):
            lines.append(f"  {i}. {action}")
        return '\n'.join(lines)


if __name__ == '__main__':
    gen = ReportGenerator()
    
    # Test report
    from src.agent.timeline import predict_failure_timeline
    timeline = predict_failure_timeline(45.0, 0.78, engine_id=47)
    
    fake_sensors = {
        'sensor2': {'name': 'Fan Speed', 'importance': 0.9, 'importance_pct': 90.0},
        'sensor7': {'name': 'HPC Pressure', 'importance': 0.7, 'importance_pct': 70.0},
        'sensor11': {'name': 'Static Pressure', 'importance': 0.5, 'importance_pct': 50.0},
    }
    
    report = gen.generate_report(
        engine_id=47,
        anomaly_prob=0.78,
        severity='HIGH',
        root_cause='Fan bearing wear detected',
        timeline=timeline,
        sensor_importance=fake_sensors,
        action_plan=['Inspect fan bearing', 'Reduce load by 20%']
    )
    print(report)